export const VERIFICATION_CUSTOMER_TEMPLATE = process.env.VERIFICATION_CUSTOMER_TEMPLATE;
export const VERIFICATION_USER_TEMPLATE = process.env.VERIFICATION_USER_TEMPLATE;
export const WELCOME_USER_TEMPLATE = process.env.WELCOME_USER_TEMPLATE;
export const WELCOME_USER_SUBJECT = process.env.WELCOME_USER_SUBJECT;
export const WELCOME_CUSTOMER_TEMPLATE = process.env.WELCOME_CUSTOMER_TEMPLATE;
export const WELCOME_CUSTOMER_SUBJECT = process.env.WELCOME_CUSTOMER_SUBJECT;
